config/routes.rb
Rails.application.routes.draw do

  resources :lists
  resources :actions

  get '/bangbang/:id', to: 'actions#show'

  mount Judge::Engine => '/judge'

  resources :albums

  resources :story_elements

  resources :task_submissions do
    member do
      get :reject
      get :accept
      get :pending
    end
  end

  resources :posts do
    collection do
      get 'suggestions'
      # get 'autocomplete_tags'
      # get 'autocomplete_mentions'
      # get 'autocomplete_bangbangs'
    end
  end

  resources :tasks

  resources :activities do
    member do
      get :deactivate
    end
  end

  resources :documents

  resources :spotlights

  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}

  resources :users do
    member do
      get :admin_edit
      put :admin_update

      get :edit_ambition
      patch :update_ambition

      get :edit_bio
      patch :update_bio

      put :update_rating
      put :update_youtube
      put :update_soundcloud
      # put :add_story_element
      # get :edit_story_element
      # put :update_story_element
      put :add_profile_photo

      get :cancel_edit
    end
    resources :story_elements
  end

  match '/add_story_element', to: "users#add_story_element", via: :post
  match '/add_activity', to: "users#add_activity", via: :post
  match '/icons', to: "pages#icons", via: :get
  match '/about', to: "pages#about", via: :get
  match '/leader_dashboard', to: "users#leader_dashboard", via: :get
  match '/admin', to: "pages#admin", via: :get

  authenticated :user do
    root to: "pages#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "pages#landing"
    match '/leaders', to: "pages#index", via: :get
  end

  # match '/landing', to: 'pages#landing', via: :get
  resources :users, :only => [:show, :edit, :update]
  resources :followships, only: [:create, :destroy]
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :assignments
  has_many :actions, through: :assignments
  belongs_to :user

  accepts_nested_attributes_for :actions, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
    @users = User.all

    @post = current_user ? current_user.posts.new : Post.new
    @posts = Post.order('created_at DESC')
    @list = List.find(params[:id])
  end

  def new
    @user = current_user
    @list = @user.lists.build
  end

  def edit
  end

  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:user_id, :title,:description, actions_attributes: [:id, :title, :description, :_destroy])
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_action_fields.html.erb
<div class="new-nested-action">
<span>!!</span>
<%= f.text_field :title, placeholder: "Another Action...", class: "nested-step-input"  %>
<%= f.text_field :description, placeholder: "Description...", class: "nested-step-input"  %>
</div>

app/views/lists/_form.html.haml
#new_list
  = form_for @list, html: {id: ''} do |f|
    - if @list.errors.any?
      #error_explanation
        %h2= "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
        %ul
          - @list.errors.full_messages.each do |msg|
            %li= msg
    .field
      .list-form-header
        .list-title
          %span //
          = f.text_field :title, placeholder: "NameYourList"
        .description-block  
          %a.list-description-link.add-plus description
          .description{style:"display:none;"}
            = f.text_area :description, placeholder: "Enter a brief description of your list"

    = f.fields_for :actions, @list.actions.build do |action|
      = render 'action_fields', f: action
    .links
      = link_to_add_association 'action', f, :actions, class: 'add-plus'
    .submit
      = f.submit 'Save'

app/views/lists/edit.html.haml
%h1 Editing list

= render 'form'

= link_to 'Show', @list
\|
= link_to 'Back', lists_path

app/views/lists/index.html.haml
.container
  .row
    .col-lg-3.sidebar
      /Trending Actions
      .trending.card
        =render 'pages/trending_actions'
      
      /Lists
      /render top 3 lists
      .lists.card
        =render 'pages/trending_lists'
      
      /Leaders
      /render top 3 local leaders
      .leaders.card
        =render 'pages/local_leaders'
    .col-lg-8
      %h1 Listing lists

      %table
        %tr
          %th User
          %th Title
          %th Description
          %th
          %th
          %th

        - @lists.each do |list|
          %tr
            %td= list.user_id
            %td= list.title
            %td= list.description
            %td= link_to 'Show', list
            %td= link_to 'Edit', edit_list_path(list)
            %td= link_to 'Destroy', list, :method => :delete, :data => { :confirm => 'Are you sure?' }

      %br

      = link_to 'New List', new_list_path

app/views/lists/new.html.haml
.container
  .row
    .col-lg-3.sidebar
      /Trending Actions
      .trending.card
        =render 'pages/trending_actions'
      
      /Lists
      /render top 3 lists
      .lists.card
        =render 'pages/trending_lists'
      
      /Leaders
      /render top 3 local leaders
      .leaders.card
        =render 'pages/local_leaders'
    .col-lg-8
      .card
        = render 'form'

app/views/lists/show.html.haml
.container
  .row
    .col-lg-3.sidebar
      /Trending Actions
      .trending.card
        =render 'pages/trending_actions'

      /Lists
      /render top 3 lists
      .lists.card
        =render 'pages/trending_lists'

      /Leaders
      /render top 3 local leaders
      .leaders.card
        =render 'pages/local_leaders'

    .col-lg-8
      #feed
        #post_field
          =form_for @post, html:{remote: true} do |f|
            =text_area_tag :query, params[:query], id: "post_form", class: 'form-control action-input', placeholder: 'What actions did you take today?', name:"post[content]", rows: 3
            #hidden_fields
            /search--if found, log tag_id. if NOT found, create new tag, log new_tag_id
            /on post submission, create tagging and create post
            = button_tag "Stay Up", class: 'btn btn-default'


        #list

          %h1
            = @list.title
          %p
            = @list.description
          %ul
            -@list.actions.each do |a|
              %li
                %a.pretty-link.bangbang-pretty-link{href:"/bangbang/1"}
                  %span !!
                  = a.title
                %p
                  = a.description