config/routes.rb
Rails.application.routes.draw do

  resources :lists
  resources :actions

  get '/bangbang/:id', to: 'actions#show'

  mount Judge::Engine => '/judge'

  resources :albums

  resources :story_elements

  resources :task_submissions do
    member do
      get :reject
      get :accept
      get :pending
    end
  end

  resources :posts do
    collection do
      get 'suggestions'
      # get 'autocomplete_tags'
      # get 'autocomplete_mentions'
      # get 'autocomplete_bangbangs'
    end
  end

  resources :tasks

  resources :activities do
    member do
      get :deactivate
    end
  end

  resources :documents

  resources :spotlights

  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}

  resources :users do
    member do
      get :admin_edit
      put :admin_update

      get :edit_ambition
      patch :update_ambition

      get :edit_bio
      patch :update_bio

      put :update_rating
      put :update_youtube
      put :update_soundcloud
      # put :add_story_element
      # get :edit_story_element
      # put :update_story_element
      put :add_profile_photo

      get :cancel_edit
    end
    resources :story_elements
  end

  match '/add_story_element', to: "users#add_story_element", via: :post
  match '/add_activity', to: "users#add_activity", via: :post
  match '/icons', to: "pages#icons", via: :get
  match '/about', to: "pages#about", via: :get
  match '/leader_dashboard', to: "users#leader_dashboard", via: :get
  match '/admin', to: "pages#admin", via: :get

  authenticated :user do
    root to: "pages#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "pages#landing"
    match '/leaders', to: "pages#index", via: :get
  end

  # match '/landing', to: 'pages#landing', via: :get
  resources :users, :only => [:show, :edit, :update]
  resources :followships, only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_merit

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history]
  def slug_candidates
    [
      :name,
      [:name, :id],
    ]
  end
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  after_create :notify_admins
  
      
  has_attached_file :profile_photo, styles: { :normal => "100%",:small => "100 x100>",:medium => "200x200>", :thumb => "50x50>", spacer: "x50" },
                                    storage: :s3,
                                    :s3_credentials => Proc.new{|a| Rails.env.production? ? a.instance.prod_s3_credentials :  a.instance.s3_credentials},
                                    :path => "/:attachment/:id/:style/:filename"


  validates_attachment_content_type :profile_photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  def prod_s3_credentials
     {:bucket => "ambition-prod", :access_key_id => ENV['S3_KEY'], :secret_access_key => ENV['S3_SECRET']}
  end
  def s3_credentials
      {:bucket => "ambition-dev", :access_key_id => ENV['S3_KEY'], :secret_access_key => ENV['S3_SECRET']}
  end
  


  has_many :assets, as: :imageable, :dependent => :destroy

  has_many :followships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_followships, foreign_key: "followed_id", class_name: "Followship", dependent: :destroy
  has_many :followers, through: :reverse_followships, source: :follower

  has_many :task_submissions
  has_many :tasks
  has_many :albums
  has_many :documents
  has_many :activities
  has_many :story_elements
  has_many :goals
  has_one  :spotlight
  has_many :posts
  has_many :lists

  has_many :user_taggings
  has_many :tags, through: :user_taggings
  has_many :user_bang_bangings
  has_many :actions, through: :user_bang_bangings


  
  accepts_nested_attributes_for :assets
  
  ######## VALIDATION ########
  validates_presence_of :name, :email
  
  
  def self.spotlit_users
    all.select do |u|
      if u.leader? && u.spotlight && u.spotlight.active?
        u
      end
    end
  end
  
  def self.leaders
    all.select{|x| x.leader?}
  end
  
  def self.admins
    all.select{|x| x.admin?}
  end
  
  def admin?
    return self.admin
  end
  
  def self.sort_by_rating
    order('rating DESC')
  end
  
  def leader?
    return self.leader
  end
  
  def following?(other_user)
    followships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    followships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    followships.find_by_followed_id(other_user.id).destroy
  end
  
  
  def notify_admins
    if Rails.env.production?
      @admins = User.admins
      @admins.each do |admin|
        AdminMailer.notify_about_sign_up(self , admin).deliver
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController


  
  
  def new
    # Override Devise default behaviour and create a profile as well
    build_resource({})
    resource.assets.build
    respond_with self.resource
  end

  def edit

    resource.assets.build
    puts params
    @user = User.friendly.find(params[:format])
    
  end
  
  def update
    @user = User.find(current_user.id)

    successfully_updated = if needs_password?(@user, params)
      @user.update_with_password(devise_parameter_sanitizer.sanitize(:account_update))
    else
      # remove the virtual current_password attribute
      # update_without_password doesn't know how to ignore it
      params[:user].delete(:current_password)
      @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))
    end

    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case their password changed
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  def after_sign_up_path_for(resource)
    user_path(current_user)
  end
  def after_update_path_for(resource)
    user_path(current_user)
  end

  private

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
  def needs_password?(user, params)
    user.email != params[:user][:email] ||
      params[:user][:password].present? ||
      params[:user][:password_confirmation].present?
  end

  
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController


  
  def create
    params[:user].merge!(remember_me: 1)
    super
  end
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show   
    @user = User.friendly.find(params[:id])
    if @user == current_user
      # @story_element = @user.story_elements.build
      unless @user.profile_photo_file_name
        @no_photo = true
      end

      unless @user.ambition
        @no_ambition = true
      end

      @items = @user.user_bang_bangings
      # @items = @items.order_by_created_at('DESC')
    end
    
    if @user.leader?
      
      @task = @user.tasks.last
    end
    
    @followers = @user.followers
    if @followers
      @followers_groups_of_three = @followers.each_slice(3)
    end
  end



  def public_profile
    @user = User.friendly.find(params[:id])
  end
  
  def add_profile_photo
    @user = User.friendly.find(params[:id])
    
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: 'Photo was successfully added.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
  end
  
  def admin_edit
    @user = User.friendly.find(params[:id])
  end
  
  def admin_update
    @user = User.friendly.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def edit_ambition
    @user = current_user
    respond_to do |format|
      format.js {@user}
    end
  end
  
  def update_ambition
    # @user = User.find(current_user.id)
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.js {}
        format.json { render @user }
      else
        format.json { render json: @activity.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @user = User.friendly.find(params[:id])
    @user.destroy
    render @user
  end
  
  def edit_bio
    @user = current_user
    respond_to do |format|
      format.js {@user}
    end
  end
  
  def update_bio
    @user = User.find(current_user.id)

    respond_to do |format|
      # puts "************" + params[:ad_lib]
      
      if params[:ad_lib] == 'ad_lib'
        # puts "%%%%%%%%%%%" + params[:ad_lib]
        # bio_params
        bio = "I come from "+ bio_params[:a] +". I believe in "+ bio_params[:b]+", "+bio_params[:c]+", and " +bio_params[:d]+". People know me for "+ bio_params[:e]+". I am committed to "+bio_params[:f]+". I hope to "+bio_params[:g]+"."
        # puts "!!!!!!!!!" + bio
        # +", ______, and ______. People know me for  ______. I am committed to ______. I hope to _______________."
        if @user.update(bio: bio)
          format.js {}
          format.json { render @user }
        else
          format.json { render json: @user.errors.full_messages, status: :unprocessable_entity }
        end
      else
        # puts "xzxzxzxzxzxzxzxzxzx"
        # bio = user_params[:bio].gsub! /\n /, "\n\n"
        bio = user_params[:bio]
        # puts bio
        if @user.update(bio: bio)
          format.js {}
          format.json { render @user }
        else
          format.json { render json: @user.errors.full_messages, status: :unprocessable_entity }
        end
      end
    end
  end
  
  def update_rating
    @user = User.find(user_params[:id])
    @user.rating = user_params[:rating]
    if @user.ambition.nil?
      @user.ambition = '.'
    end
    @user.save!
    respond_to do |format|
      if @user.save
        format.html { render @user}
      else
        format.html { render @user}
      end
    end
  end
  
  def update_youtube
    @user = User.find(user_params[:id])
    @user.youtube_id = user_params[:youtube_id]
    if @user.ambition.nil?
      @user.ambition = '.'
    end
    @user.save!
    respond_to do |format|
      if @user.save
        format.html { render @user}
      else
        format.html { render @user}
      end
    end
  end
  
  def update_soundcloud
    @user = User.find(user_params[:id])
    @user.soundcloud_id = user_params[:soundcloud_id]
    if @user.ambition.nil?
      @user.ambition = '.'
    end
    @user.save!
    respond_to do |format|
      if @user.save
        format.html { render @user}
      else
        format.html { render @user}
      end
    end
  end
  

  
  
  def leader_dashboard
    @user = current_user
    @tasks = @user.tasks
  end
  
  def add_photos
    @user = current_user
    @assets = @user.assets.build
  end
  
  def index
    @users = User.order('rating DESC')
  end


private
  def user_params
    params.require(:user).permit(:id, :ambition, :name, :bio,:youtube_id,:soundcloud_id, :rating, :profile_photo, bio_pieces: [:a, :b, :c, :d, :e, :f, :g])
  end
  def bio_params
    params.require(:bio_pieces).permit(:a, :b,:c, :d, :e, :f, :g)
  end
  
end

app/views/users/_bio.html.haml
.user-bio
  -if current_user && current_user === @user
    -if @user.bio
      %p=simple_format @user.bio
      =link_to "Edit", edit_bio_user_path(@user), remote:true, class: "user-edit-button"
    -else
      #bio_field
      
        / =link_to "Guided Bio", "#", id: "guided_form_button", style: "pointer-events: none; cursor: default;"
        / |
        / =link_to "Free Form Bio", "#", id: "free_form_button"
        / %p hello
        =render "bio_field"
        
  -else
    %p=simple_format @user.bio, {}, wrapper_tag: "p"

app/views/users/_followers.html.haml
-if @followers_groups_of_three
  .row
    .col-lg-12
      -@followers_groups_of_three.each do |f3|
        .row.team-row
          -f3.each_with_index do |f, i|
            .col-md-4
              .follower-pic-name.text-center
                .round-thumbnail
                  =link_to image_tag(f.profile_photo_file_name ? f.profile_photo.url(:small) : '/assets/user-placeholder-follower.png', :alt => f.name, class: "circle-image"), user_path(f)
                %p=f.name
  / -@followers.each_with_index do |f, i|
  /   %div{class: "#{ i % 3 == 0 || i == 0 ? 'row' : ''}" }
  /   .col-sm-4
  /     .follower-pic-name.text-center
  /       .round-thumbnail
  /         =link_to image_tag(f.profile_photo_file_name ? f.profile_photo.url(:small) : '/assets/user-placeholder-follower.png', :alt => f.name, class: "circle-image"), user_path(f)
  /       %p=f.name

app/views/users/_show_leader.html.haml
.row
  .col-lg-3
    .profile-pic
      .round-border
        .round.round-center          
          =link_to image_tag(@user.assets.empty?  ? '/assets/user-placeholder.png': @user.assets.first.image.url(:medium), :alt => @user.name, class: "circle-image"), user_path(@user)
      .text-center
        %h2
          =@user.name
        %h2
          -if current_user && current_user == @user
            =link_to "Edit Details", edit_user_registration_path(current_user), style:"font-size:50%"
            -if @user.leader?
              =link_to "Your Dashboard", leader_dashboard_path, style:"font-size:50%"
        
          
    / USERS SOCIAL MEDIA
    
    .social-media-box.text-center
      
      
      

        
      -if @user.facebook_url.nil?
        -if current_user && current_user == @user
          %i.fa.fa-facebook.fa-2x.facebook-blue
          %p You haven't added your fb profile yet. #{link_to 'Add it', edit_user_registration_path(current_user), class: "btn btn-mini btn-primary make-button"}
      -else
        = link_to '<i class="fa fa-facebook fa-2x facebook-blue"></i>'.html_safe, "#{@user.facebook_url}"
      -if @user.twitter_url.nil?
        -if current_user && current_user == @user
          %i.fa.fa-twitter.fa-2x.twitter-blue
          %p You haven't added your twitter profile yet. #{link_to 'Add it', edit_user_registration_path(current_user), class: "btn btn-mini btn-primary make-button"}
      -else
        = link_to '<i class="fa fa-twitter fa-2x twitter-blue"></i>'.html_safe, "#{@user.twitter_url}"

  
  .col-lg-9

    %h2
      - unless current_user == @user
        #follow_form
          - if current_user && current_user.following?(@user)
            = render 'unfollow'
            
          - elsif current_user.nil?
            =link_to "Join the Following", new_user_registration_path, class: "btn btn-large btn-primary make-button"
          -else
            = render 'follow'
            / -unless @task.nil?
            /   =link_to "Join the Following", new_task_submission_path(task_id: @task.id), class: "btn btn-large btn-primary make-button"
          
    %h3=@user.occupation    
    
    
    
    /BIO
    .row
      .col-lg-7
        .bio
          %p=@user.bio
        .photos
          / -@user.assets.each do |image|
          /   =image_tag( image.image.url(:thumb), :alt => @user.name, class: "")
          -@user.albums.each do |album|
            -album.assets.each do |a|
              =image_tag(a.image.url(:medium), :alt => @user.name, class: "circle-image")
    
    
        /AMBITION
        %h3 Ambition
        %p=@user.ambition
        %br/
        
        /CURRENT ACTIVITIES
        %h3 What I'm doing right now
        %p=@user.current_activities
        
        /PHOTO ALBUM
        =link_to "Add Photos", new_album_path
        
    /FOLLOWER OF THE WEEK
    
    /YOUR FOLLOWING
    -if @followers
      %h3 Leader's Followers:
      -@followers.each do |f|
        .round-thumbnail
          =link_to image_tag(f.assets.empty?  ? '/assets/user-placeholder-thumbnail.png': f.assets.first.image.url(:small), :alt => f.name, class: "circle-image"), user_path(f)
        %p=f.name
    
    /BADGES?
    

    
    
    /MORNING ROUTINE
    
    
    /SPONSORS? - maybe some companies want to sponsor these community leaders because kids will be looking up to them

app/views/users/_timeline.html.haml
.story-elements.text-center
  #story_form
    -if @user.story_elements.first && @user.story_elements.first.improvement
      -@user.story_elements.each_with_index do |se, i|
        
        %div{id: "story_element_#{se.id}"}
          -unless se.new_record?
            =render partial: "story_elements/story_element", locals: {story_element: se }
          

            -unless i == @user.story_elements.size - 2
              .long-line

    -else
      -if current_user && current_user === @user
        .story-element-form
        
        =render partial: "story_elements/story_element", locals: {story_element: @story_element}

app/views/users/_unfollow.html.haml
= form_for(current_user.followships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f|
  = f.submit "Unfollow", class: "btn btn-large"                             

app/views/users/_user.html.haml
.user-list-card
  .row
    .col-lg-12
      .link-container       
        .user-list-card-image
          =link_to image_tag(user.profile_photo_file_name.nil?  ? '/assets/user-placeholder.png': user.profile_photo.url(:medium), :alt => user.name, class: "circle-image"), user_path(user)
        .user-card-details
          =link_to user.name, user_path(user), class: 'user-list-card-name'
          %p=truncate(user.bio,20)
    
    /make whole card linkable
    %a{href: "#{user_path(user)}" }
      %span.user-list-card-link-spanner
      

app/views/users/admin_edit.html.haml
-if current_user && current_user.admin?
  =form_for(@user, url: admin_update_user_path(@user), html:{method: :put}) do |f|
    .profile-pic
      .round-border
        .round.round-center
          -if @user.profile_photo_file_name
            =link_to image_tag(@user.profile_photo.nil?  ? '/assets/user-placeholder.png' : @user.profile_photo.url(:medium), :alt => @user.name, class: "circle-image"), user_path(@user)
          -else
            =link_to image_tag(@user.assets.empty?  ? '/assets/user-placeholder.png': @user.assets.first.image.url(:medium), :alt => @user.name, class: "circle-image"), user_path(@user)
    .form-group

      .image-field
        = f.file_field :profile_photo, type:"file"
    
    =f.submit "Update", class: "btn btn-primary submit-button follow-button"

app/views/users/edit_ambition.js.erb
$("#ambition").html("<%= escape_javascript(render 'ambition_field') %>")

app/views/users/edit_goal.js.erb
$("#goal").html("<%= escape_javascript(render 'users/goals/goal_field') %>")

app/views/users/index.html.haml
.row
  .col-lg-2
  .col-lg-8
    .hero
      %h1 Ambition Spotlight
      /new logo
    .users
      =render @users
      .users-cta.landing-buttons.landing-first.text-center
        =link_to "Get Your Profile Now", new_user_registration_path, class: "btn btn-large btn-primary make-button landing-button"

app/views/users/leader_dashboard.html.haml
%h1 Tasks
=link_to "Create a Task", new_task_path

-@tasks.each do |task|
  %p=task.description
  %ul
    -task.task_submissions.each do |ts|
      %li
        -unless ts.user.nil?
          =ts.user.name
        -unless ts.description.nil?
          =ts.description
        -if ts.status == 'pending'
          = link_to 'Reject', reject_task_submission_path(ts), :class => 'btn btn-mini btn-danger'
          = link_to 'Accept', accept_task_submission_path(ts), :class => 'btn btn-mini btn-success'
        -elsif ts.status == 'rejected'
          = link_to 'Undo Rejection', pending_task_submission_path(ts), :class => 'btn btn-mini btn-primary'
          = link_to 'Accept', accept_task_submission_path(ts), :class => 'btn btn-mini btn-success'
        -else
          = link_to 'reject', reject_task_submission_path(ts), :class => 'btn btn-mini btn-danger'
          = link_to 'Undo Accepting', pending_task_submission_path(ts), :class => 'btn btn-mini btn-primary'

app/views/users/public_profile.html.haml
/VERSION 2

.row
  .col-lg-2
  .user-card-container
    .col-lg-8.user-card          
      .text-center
        %h1.name
          =@user.name
      .profile-pic
        .round-border
          .round.round-center
            -if @user.profile_photo_file_name
              =image_tag(@user.profile_photo.nil?  ? '/assets/user-placeholder.png': @user.profile_photo.url(:medium), :alt => @user.name, class: "circle-image")
            -else
              =image_tag(@user.assets.empty?  ? '/assets/user-placeholder.png': @user.assets.first.image.url(:medium), :alt => @user.name, class: "circle-image")
      #ambition
      .text-center 
        .story
          .story-header
            %p
              WHERE I WANT TO BE IN 5 YEARS
          .story-text#ambition
            =render partial: 'ambition', locals: {user: @user}
            /%p=@user.ambition
            / -if current_user && current_user == @user
            /   %span.text-center.edit-link=link_to "Edit Details", edit_user_registration_path(current_user)
          
            
            
            / -if @user.leader?
            /   =link_to "Your Dashboard", leader_dashboard_path, style:"font-size:50%"
            
          =render partial: 'shared/follow', locals: {user: @user}
          - content_for :head do
            %meta{:content => "Ambition Spotlight | #{@user.name}", :property => "og:title"}
            %meta{:content => "#{@user.ambition}", :property => "og:description"}
            %meta{:content => "http://www.ambitionspotlight.com" + user_path(@user), :property => "og:url"}
            
            %meta{:content => "#{@user.profile_photo_file_name.nil?  ? '/assets/user-placeholder.png': @user.profile_photo.url(:medium)}", :property => "og:image"} 
            %meta{property: "og:type", content:"article"} 
          

          .share.text-center
            %a{class: "fb-share-link btn btn-large make-button follow-button", "data-name"=> "#{@user.name}", "data-link"=> "http://www.ambitionspotlight.com#{user_path(@user)}", "data-image" => "#{@user.profile_photo.nil?  ? '/assets/user-placeholder.png': @user.profile_photo.url(:medium)}", "data-description"=>"#{@user.ambition}"}
              %i.fa.fa-facebook.fb-icon
              | Share My Story
        
        #doing

        #bio
        .story
          .story-header
            %p
              WHO I AM

          .story#bio
            =render partial: 'bio', locals: {user: @user}
              /render bda

        #timeline
        /TIMELINE WITH UPDATE
        .story
          .story-header
            %p MY GROWTH
          .story#timeline
            =render partial: 'timeline', locals: {user: @user}
        
        #believers
        /YOUR FOLLOWING
        .story
          .story-header
            %p WHO BELIEVES IN ME
            /have a "share profile" link or something to post on facebook
          
          .follow_form
            - if current_user && current_user.following?(@user)
              = render 'unfollow'

            - elsif current_user.nil?
              =link_to "I BELIEVE", new_user_registration_path, class: "btn btn-large make-button follow-button"
            -else
              = form_for(current_user.followships.build(followed_id: @user.id), remote: true) do |f|
                %div
                  = f.hidden_field :followed_id
                = f.submit "I BELIEVE", class: "btn btn-large follow-button"
          %br/
          
          .following
            #followers
              =render partial: 'followers', locals: {followers: @followers}

      

app/views/users/update_ambition.js.erb
$("#ambition").html("<%= escape_javascript(render('ambition')) %>")

app/views/users/update_bio.js.erb
$("#bio").html("<%= escape_javascript(render('bio')) %>")