config/routes.rb
Rails.application.routes.draw do

  resources :lists
  resources :actions

  get '/bangbang/:id', to: 'actions#show'

  mount Judge::Engine => '/judge'

  resources :albums

  resources :story_elements

  resources :task_submissions do
    member do
      get :reject
      get :accept
      get :pending
    end
  end

  resources :posts do
    collection do
      get 'suggestions'
      # get 'autocomplete_tags'
      # get 'autocomplete_mentions'
      # get 'autocomplete_bangbangs'
    end
  end

  resources :tasks

  resources :activities do
    member do
      get :deactivate
    end
  end

  resources :documents

  resources :spotlights

  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}

  resources :users do
    member do
      get :admin_edit
      put :admin_update

      get :edit_ambition
      patch :update_ambition

      get :edit_bio
      patch :update_bio

      put :update_rating
      put :update_youtube
      put :update_soundcloud
      # put :add_story_element
      # get :edit_story_element
      # put :update_story_element
      put :add_profile_photo

      get :cancel_edit
    end
    resources :story_elements
  end

  match '/add_story_element', to: "users#add_story_element", via: :post
  match '/add_activity', to: "users#add_activity", via: :post
  match '/icons', to: "pages#icons", via: :get
  match '/about', to: "pages#about", via: :get
  match '/leader_dashboard', to: "users#leader_dashboard", via: :get
  match '/admin', to: "pages#admin", via: :get

  authenticated :user do
    root to: "pages#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "pages#landing"
    match '/leaders', to: "pages#index", via: :get
  end

  # match '/landing', to: 'pages#landing', via: :get
  resources :users, :only => [:show, :edit, :update]
  resources :followships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.haml
.text-center.footer-social
  %p Follow us on #{link_to 'Facebook', "https://www.facebook.com/SuaveFx"} and #{link_to 'Twitter', "https://twitter.com/SuaveFx"}
  / = link_to '<i class="fa fa-facebook fa-2x"></i>'.html_safe, "https://www.facebook.com/SuaveFx"
  / = link_to '<i class="fa fa-twitter fa-2x"></i>'.html_safe, "https://twitter.com/SuaveFx"

app/views/layouts/_header.html.haml
%nav{role: "navigation", class: "#{@landing_page ? 'navbar-negative' : 'navbar'}" }
  .nav-container
    / Brand and toggle get grouped for better mobile display
    .row
      .nav-center
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .navbar-brand
            / .logo
            /   =image_tag "as-logo2-white.png", id: "logo"
            .masthead
              =link_to '!!bangbang', root_path, class: "masthead-link"
              /=link_to image_tag("AS-Logo.png", class: "masthead-img") , root_path, class: "masthead-link"
              .masthead-spotlight
      
      
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.pull-right              
            %li{:class => "#{'active' if current_page?(about_path)} underline-glow"}=link_to "ABOUT", about_path
            %li{:class => "#{'active' if current_page?(users_path)} underline-glow"}=link_to "SPOTLIGHT", users_path
      
            /SEARCH
            / %li
            /   %a{:href => "#"} Users
            / %form.navbar-form.navbar-left{:role => "search"}
            /   .form-group
            /     %input.form-control{:placeholder => "Search", :type => "text"}
            /   %button.btn.btn-default{:type => "submit"}
            /     =link_to "", "#"
            /     %span.glyphicon.glyphicon-large.glyphicon-search
            /   %i.icon-large.icon-search

            -if user_signed_in?
              %li{:class => "#{'active' if current_page?(lists_path)} underline-glow"}=link_to "LISTS", lists_path

              %li{:class => "#{'active' if current_page?(user_path(current_user))} dropdown user-icon"}
                
                %a.glyphicon.glyphicon-user.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}        
                  /=image_tag "user_icon.png", class: "user-icon"
                  /.user-icon.pull-left
                  /%b.caret
                %ul.dropdown-menu
                  %p.nav-you YOU
                  %li
                    =link_to current_user.name, user_path(current_user)
                  / %li
                  /   =link_to "Settings", user_settings_path
                  / %li
                  /   = link_to "Sign Up", new_user_registration_path
                  %li
                    =link_to 'Settings', edit_user_registration_path(current_user)
                    
                  %li
                    =link_to "Sign out", destroy_user_session_path, :method => :delete
                
                
              / %li
              /   =link_to "SIGN OUT", destroy_user_session_path, :method => :delete
            -else
              %li.underline-glow
                =link_to "SIGN UP", new_user_registration_path
              / %li
              /   = link_to "Sign Up", new_user_registration_path
              %li.underline-glow
                =link_to "SIGN IN", new_user_session_path

app/views/layouts/_sidebar.html.haml
/Trending Actions
.trending.card
  =render 'pages/trending_actions'

/Lists
/render top 3 lists
.lists.card
  =render 'pages/trending_lists'

/Leaders
/render top 3 local leaders
.leaders.card
  =render 'pages/local_leaders'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title !!
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %link{:href => "http://fonts.googleapis.com/css?family=Lato:300,400,700", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    = yield :head
    = yield :javascript

  %body{ class: "controller-specific-style-#{action_name} controller-specific-style-#{controller_name}"}
    -if @landing_page
      .overlay
        %video#video_wrapper{"?wmode" => "transparent", :autoplay => "", :loop => "", :muted => ""}
          %source{src:"EPA-landingpage.mp4", type:"video/mp4"}

    .overlayx
      .wrapper
        .container
        = render 'layouts/header'
        .container
          .content
            %p.notice.text-center= notice
            %p.alert= alert
            = yield

    - if current_user
      :javascript
        FS.identify("#{current_user.id}", {
        displayName: "#{current_user.name}",
        email: "#{current_user.email}"
        });